version: '2'
services:
    cargotracker-app:
        image: cargotracker
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cargotracker-mysql:3306/cargotracker?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://cargotracker-elasticsearch:9200
        ports:
            - 8080:8080
    cargotracker-mysql:
        extends:
            file: mysql.yml
            service: cargotracker-mysql
    cargotracker-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cargotracker-elasticsearch
